### ISSUE TITLE
enable handling selectors

### ISSUE THREAD

**Issue by beckermr** [conda/grayskull#25]
Per our gitter discussion, duplicate keys with selectors present special challenges.

**Comment by marcelotrevisani** [comment]
Hi @beckermr ,
I remember that you sent a link to a python notebook with some examples, I can't find it, sorry
Could you please add the link to it here?

**Comment by beckermr** [comment]
https://gist.github.com/beckermr/870414e5f168d3aec7f0d9e1c91adccf

**Comment by bollwyvl** [comment]
Here is a concrete example of weird selector behavior `spacy`, from [~3.2.0/3.3.0](https://github.com/explosion/spaCy/blob/v3.2.3/setup.cfg#L34)

https://github.com/conda-forge/spacy-feedstock/pull/121#issuecomment-1113368269

**Comment by marcelotrevisani** [comment]
This issue was fixed I believe. Please feel free to open another one or reopen this one if not.
