### ISSUE TITLE
[BUG] Github-pages fails to deploy

### ISSUE THREAD

**Issue by BastianZim** [conda/grayskull#324]
Not sure if you're already aware of this but the GitHub pages cannot be deployed. 

Ref https://github.com/conda-incubator/grayskull/pull/298

**Comment by marcelotrevisani** [comment]
yes, indeed, it is missing this part
@ForgottenProgramme was taking a look into it, but I think we forgot to add this bit to deploy it

**Comment by marcelotrevisani** [comment]
this one was fixed already, thanks!
