### ISSUE TITLE
Graduate grayskull to conda main organization

### ISSUE THREAD

**Issue by jezdez** [conda/grayskull#436]
@conda-incubator/steering

This vote falls under the **"[Incorporate a Software Project into the main conda Organization](https://github.com/conda-incubator/governance#incorporate-a-software-project-into-the-main-conda-organization)"** policy of the [conda governance policy](https://github.com/conda-incubator/governance), please vote and/or comment on this proposal at your earliest convenience.

It needs **60 %** of the Steering Council to vote `yes` to pass.

To vote, please leave `yes`, `no` or `abstain` as comments below.

If you have questions concerning the proposal, you may also leave a comment or code review.

**This vote will end on 2022-02-07, End of Day, [Anywhere on Earth](https://time.is/Anywhere_on_Earth) (AoE).**

Note, @marcelotrevisani has asked me to call for the vote.

**Comment by xhochy** [comment]
yes

**Comment by beckermr** [comment]
Yes

**Comment by marcelotrevisani** [comment]
Yes

**Comment by ocefpaf** [comment]
Yes

**Comment by jezdez** [comment]
> Yes
> not sure if I should vote 😄

To my knowledge, the governance policy doesn't exclude maintainers of incubator projects who happen to be on the steering council from voting.

**Comment by chenghlee** [comment]
Yes

**Comment by goanpeca** [comment]
Yes

**Comment by goanpeca** [comment]
yes

**Comment by mariusvniekerk** [comment]
yes

**Comment by msarahan** [comment]
Yes

**Comment by jakirkham** [comment]
Yes

**Comment by jezdez** [comment]
## Voting Results

This was a standard, non-timed-out vote.

Among [Steering Council members](https://github.com/conda-incubator/governance/blob/a2059652e1d41ecf3921c69b3ca4f058abde0b2a/steering.csv) there are 9 "yes", 0 "no", and no abstentions.

This vote **has reached quorum** (9 is at least 60% of 15).

It **has also passed** since it recorded 9 "yes" votes and 0 "no" votes giving 9/9 which is greater than 60% of 9.

**Comment by jezdez** [comment]
Just a few things I've done just now to facilitate the successful vote:

- recreated the grayskull team here as well
- transferred the repo from the incubator organization and assigned it with maintain permissions to grayskull team
- opened #443 to fix some URLs and badges
- opened #444 to add CODEOWNERS
- I've added a branch protection for the main branch (as a suggestion based on the experience with limiting scope in other repos, please let me know if you'd like to change any of these):
  - require a pull request before mergin
  - require 1 approval
  - require status check to pass (with the py3.8, 3.9, 3.10 and 3.11 run checks required, not pre-commit)
  - do not allow bypassing the above settings, e.g. admins
  - restrict who can push to the main branch to grayskull team
- removed painter-bot from repo
- updated precommit to run in the repo

**Comment by marcelotrevisani** [comment]
Perfect! thanks @jezdez !

**Comment by jezdez** [comment]
Just opened https://github.com/conda/infrastructure/pull/680 to automatically sync the Code of Conduct into the repo via PRs like we do with other projects.

**Comment by jezdez** [comment]
I think we're done for now, if you have any GitHub org related issues, don't hesitate to ping me or open an issue in https://github.com/conda/infrastructure.

Welcome @conda/grayskull! 🎉
