### ISSUE TITLE
[BUG] File URL on Windows

### ISSUE THREAD

**Issue by Luigicube** [conda/grayskull#448]
**Bug description**
Using the "local sdist archive" workflow on Windows yields an URL that is not compatible with conda-build, see:
"source:
  url: file://D:\temp\myPackage-0.0.2.tar.gz"
instead of "source:
  url: file:///D:/temp/myPackage-0.0.2.tar.gz"

**To Reproduce**
1. Using the "local sdist archive" workflow on Windows, e.g. grayskull pypi ./pytest-5.3.5.tar.gz 
2. Try using conda-build on the generated meta.yaml

**Expected behavior**
conda-build works - or at least manages to "download" the source.

**Environment:**
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/lmaviel/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/lmaviel/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Name | Version | Build | Channel
-- | -- | -- | --
beautifulsoup4 | 4.11.2 | pyha770c72_0 | conda-forge
brotlipy | 0.7.0 | py311ha68e1ae_1005 | conda-forge
bzip2 | 1.0.8 | h8ffe710_4 | conda-forge
ca-certificates | 2022.12.7 | h5b45459_0 | conda-forge
certifi | 2022.12.7 | pyhd8ed1ab_0 | conda-forge
cffi | 1.15.1 | py311h7d9ee11_3 | conda-forge
chardet | 5.1.0 | py311h1ea47a8_0 | conda-forge
charset-normalizer | 2.1.1 | pyhd8ed1ab_0 | conda-forge
colorama | 0.4.6 | pyhd8ed1ab_0 | conda-forge
conda | 22.11.1 | py311h1ea47a8_1 | conda-forge
conda-build | 3.23.3 | py311h1ea47a8_1 | conda-forge
conda-package-handling | 2.0.2 | pyh38be061_0 | conda-forge
conda-package-streaming | 0.7.0 | pyhd8ed1ab_1 | conda-forge
conda-souschef | 2.2.3 | pyhd8ed1ab_0 | conda-forge
cryptography | 39.0.1 | py311h28e9c30_0 | conda-forge
filelock | 3.9.0 | pyhd8ed1ab_0 | conda-forge
glob2 | 0.7 | py_0 | conda-forge
grayskull | 2.2.2 | pyhd8ed1ab_0 | conda-forge
idna | 3.4 | pyhd8ed1ab_0 | conda-forge
intel-openmp | 2023.0.0 | h57928b3_25922 | conda-forge
jinja2 | 3.1.2 | pyhd8ed1ab_1 | conda-forge
libarchive | 3.6.2 | h27c7867_0 | conda-forge
libblas | 3.9.0 | 16_win64_mkl | conda-forge
libcblas | 3.9.0 | 16_win64_mkl | conda-forge
libffi | 3.4.2 | h8ffe710_5 | conda-forge
libhwloc | 2.8.0 | h039e092_1 | conda-forge
libiconv | 1.17 | h8ffe710_0 | conda-forge
liblapack | 3.9.0 | 16_win64_mkl | conda-forge
liblief | 0.12.3 | h63175ca_0 | conda-forge
libsqlite | 3.40.0 | hcfcfb64_0 | conda-forge
libxml2 | 2.10.3 | hc3477c8_0 | conda-forge
libzlib | 1.2.13 | hcfcfb64_4 | conda-forge
lz4-c | 1.9.4 | hcfcfb64_0 | conda-forge
lzo | 2.10 | he774522_1000 | conda-forge
m2-msys2-runtime | 2.5.0.17080.65c939c | 3 | conda-forge
m2-patch | 2.7.5 | 2 | conda-forge
m2w64-gcc-libgfortran | 5.3.0 | 6 | conda-forge
m2w64-gcc-libs | 5.3.0 | 7 | conda-forge
m2w64-gcc-libs-core | 5.3.0 | 7 | conda-forge
m2w64-gmp | 6.1.0 | 2 | conda-forge
m2w64-libwinpthread-git | 5.0.0.4634.697f757 | 2 | conda-forge
markupsafe | 2.1.2 | py311ha68e1ae_0 | conda-forge
menuinst | 1.4.19 | py311h1ea47a8_1 | conda-forge
mkl | 2022.1.0 | h6a75c08_874 | conda-forge
msys2-conda-epoch | 20160418 | 1 | conda-forge
numpy | 1.24.2 | py311h0b4df5a_0 | conda-forge
openssl | 3.0.8 | hcfcfb64_0 | conda-forge
packaging | 23.0 | pyhd8ed1ab_0 | conda-forge
pip | 23.0.1 | pyhd8ed1ab_0 | conda-forge
pkginfo | 1.9.6 | pyhd8ed1ab_0 | conda-forge
pluggy | 1.0.0 | pyhd8ed1ab_5 | conda-forge
progressbar2 | 4.2.0 | pyhd8ed1ab_0 | conda-forge
psutil | 5.9.4 | py311ha68e1ae_0 | conda-forge
pthreads-win32 | 2.9.1 | hfa6e2cd_3 | conda-forge
py-lief | 0.12.3 | py311h12c1d0e_0 | conda-forge
pycosat | 0.6.4 | py311ha68e1ae_1 | conda-forge
pycparser | 2.21 | pyhd8ed1ab_0 | conda-forge
pyopenssl | 23.0.0 | pyhd8ed1ab_0 | conda-forge
pysocks | 1.7.1 | pyh0701188_6 | conda-forge
python | 3.11.0 | hcf16a7b_0_cpython | conda-forge
python-libarchive-c | 4.0 | py311h1ea47a8_2 | conda-forge
python-utils | 3.5.2 | pyhd8ed1ab_0 | conda-forge
python_abi | 3.11 | 3_cp311 | conda-forge
pytz | 2022.7.1 | pyhd8ed1ab_0 | conda-forge
pyyaml | 6.0 | py311ha68e1ae_5 | conda-forge
rapidfuzz | 2.13.7 | py311h12c1d0e_0 | conda-forge
requests | 2.28.2 | pyhd8ed1ab_0 | conda-forge
ripgrep | 13.0.0 | h7f3b576_2 | conda-forge
ruamel.yaml | 0.17.21 | py311ha68e1ae_2 | conda-forge
ruamel.yaml.clib | 0.2.7 | py311ha68e1ae_1 | conda-forge
ruamel.yaml.jinja2 | 0.2.4 | py_1 | conda-forge
setuptools | 59.8.0 | py311h1ea47a8_1 | conda-forge
six | 1.16.0 | pyh6c4a22f_0 | conda-forge
soupsieve | 2.3.2.post1 | pyhd8ed1ab_0 | conda-forge
stdlib-list | 0.8.0 | pyhd8ed1ab_0 | conda-forge
tbb | 2021.7.0 | h91493d7_1 | conda-forge
tk | 8.6.12 | h8ffe710_0 | conda-forge
toml | 0.10.2 | pyhd8ed1ab_0 | conda-forge
tomli | 2.0.1 | pyhd8ed1ab_0 | conda-forge
tomli-w | 1.0.0 | pyhd8ed1ab_0 | conda-forge
toolz | 0.12.0 | pyhd8ed1ab_0 | conda-forge
tqdm | 4.64.1 | pyhd8ed1ab_0 | conda-forge
tzdata | 2022g | h191b570_0 | conda-forge
ucrt | 10.0.22621.0 | h57928b3_0 | conda-forge
urllib3 | 1.26.14 | pyhd8ed1ab_0 | conda-forge
vc | 14.3 | hb6edc58_10 | conda-forge
vs2015_runtime | 14.34.31931 | h4c5c07a_10 | conda-forge
wheel | 0.38.4 | pyhd8ed1ab_0 | conda-forge
win_inet_pton | 1.1.0 | pyhd8ed1ab_6 | conda-forge
xz | 5.2.6 | h8d14728_0 | conda-forge
yaml | 0.2.5 | h8ffe710_2 | conda-forge
zstandard | 0.19.0 | py311he5d195f_1 | conda-forge
zstd | 1.5.2 | h12be248_6 | conda-forge

</body>
</html>

` - grayskull --version 2.2.2`

**Additional context**
Solution? 
https://stackoverflow.com/questions/11687478/convert-a-filename-to-a-file-url

**Comment by dihm** [comment]
Came across this problem trying to script building conda packages from python source tarballs. The offending code is here
https://github.com/conda/grayskull/blob/0e7db2717422fd197f2c7db5689d1009ff05249b/grayskull/strategy/py_base.py#L795-L799

I'll put together a 1-line PR to fix it based on @Luigicube's suggestion.
