### ISSUE TITLE
[FEATURE] Allow github tags / not releases

### ISSUE THREAD

**Issue by dholth** [conda/grayskull#451]
Grayskull should document its support for github url's. It just says pypi package name at the moment.

```
positional arguments:
  pypi_packages         Specify the PyPI packages name.
```

Grayskull should allow you to use a tag or a revision, instead of always looking for the "latest release". e.g. a prerelease is not the latest release.

Should let you point at a local folder.

**Comment by dholth** [comment]
Can grayskull point at a private github repository?

**Comment by marcelotrevisani** [comment]
> Can grayskull point at a private github repository?

yes it is possible. But the user needs to configure its credentials before running grayskull

**Comment by marcelotrevisani** [comment]
> Specify the PyPI packages name

you can specify a version doing something like
```bash
grayskull pypi pytest=7.1.0
```
it does accept specifying a version like that, I hope that help :)

**Comment by marcelotrevisani** [comment]
Grayskull also have the ``--tag`` option that you added right? :D
So, I am closing this, but if you think that is not complete feel free to reopen it or to create another issue. Thanks! :)
