### ISSUE TITLE
[FEATURE] Populate about.summary item in meta.yaml with description from setup files

### ISSUE THREAD

**Issue by CatChenal** [conda/grayskull#452]
I've just used grayskull to create the conda recipe meta.yaml file. On first try, the conda-forge-linter complained about the omission of the summary item in the about section:
> The summary item is expected in the about section.

It would be great if grayskull would populate this summary with the description string from setup.py (or any other setup file that is used).

**Additional context**
This summary item is a requirement on conda-forge staged recipes: my PR could not be merge for that single reason.
Thanks!

**Comment by marcelotrevisani** [comment]
I think we can add this as an optional, because there are a lot of cases that the summary is huge, maybe an option like, ``--add-summary`` or something might be interesting
