### ISSUE TITLE
Specify destination folder for the generated meta.yml file

### ISSUE THREAD

**Issue by ubaldot** [conda/grayskull#469]
At the moment:

`[greyskull]... will create a folder with the same name as the package and inside this folder the generated recipe will be present (meta.yaml).`

It would be nice to add a flag so that user can specify a different destination folder.

**Comment by marcelotrevisani** [comment]
there is an option ``-o`` or ``--output`` so you can specify a path for the recipe.
Does this work for you?

**Comment by ubaldot** [comment]
Yes. :)

**Comment by marcelotrevisani** [comment]
cool cool! I am closing this issue then, if you find any problems or features requests that would be nice, please feel free to open a new issue

Cheers!

**Comment by ubaldot** [comment]
Not connected to grayskull but with conda: docs, docs, docs! Not quantity but *quality*.

**Comment by marcelotrevisani** [comment]
indeed, that is a thing that we need to improve and we should improve :sweat_smile:

**Comment by ubaldot** [comment]
Only because of that I think to switch back to Matlab every second day. 

… just kidding: it happens twice per day. 

One last thing: please install xdg-open to the Azure linux runners (conda-forge pipeline).
