### ISSUE TITLE
[BUG] Grayskull fails to guess correctly the name of the executable when it differs from the package name

### ISSUE THREAD

**Issue by jbdavid5027** [conda/grayskull#475]
**Describe the bug**
When building the meta.yaml file for a pypi project packaged with flit_core as mentioned in the pyproject.toml 
it incorrectly specifies that the host requires flit_core >=2,<4 , 
where the correct specification is flit-core >=2,<4 
due to the as built name is not the same as project name on pypi

**To Reproduce**
1.  create a conda env for python 3.10 with conda-build, grayskull and flit_core 
2. activate the environment as in the grayskull tutorial
3.  use "grayskull pypi inform" to create the build recipe
4.  use "conda-build inform" to build the package 
5. observe the error message "conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform win-64: {"flit_core[version='>=2,<4']"}

**Expected behavior**
the requirement should have been flit-core and not flit_core despit the name working in the pyproject.toml 

**Outputs**
Traceback (most recent call last):
  File "C:\Users\jdavid\.conda\envs\conda-build310\lib\site-packages\conda_build\environ.py", line 900, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "C:\Users\jdavid\.conda\envs\conda-build310\lib\site-packages\conda\common\io.py", line 83, in decorated
    return f(*args, **kwds)
  File "C:\Users\jdavid\.conda\envs\conda-build310\lib\site-packages\conda\plan.py", line 535, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "C:\Users\jdavid\.conda\envs\conda-build310\lib\site-packages\conda\core\solve.py", line 153, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(
  File "C:\Users\jdavid\.conda\envs\conda-build310\lib\site-packages\conda\core\solve.py", line 214, in solve_for_diff
    final_precs = self.solve_final_state(
  File "C:\Users\jdavid\.conda\envs\conda-build310\lib\site-packages\conda\core\solve.py", line 379, in solve_final_state
    ssc = self._add_specs(ssc)
  File "C:\Users\jdavid\.conda\envs\conda-build310\lib\site-packages\conda\core\solve.py", line 732, in _add_specs
    explicit_pool = ssc.r._get_package_pool(self.specs_to_add)
  File "C:\Users\jdavid\.conda\envs\conda-build310\lib\site-packages\conda\resolve.py", line 649, in _get_package_pool
    pool = self.get_reduced_index(specs)
  File "C:\Users\jdavid\.conda\envs\conda-build310\lib\site-packages\conda\common\io.py", line 83, in decorated
    return f(*args, **kwds)
  File "C:\Users\jdavid\.conda\envs\conda-build310\lib\site-packages\conda\resolve.py", line 674, in get_reduced_index
    explicit_specs, features = self.verify_specs(explicit_specs)
  File "C:\Users\jdavid\.conda\envs\conda-build310\lib\site-packages\conda\resolve.py", line 329, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound:
  - flit_core[version='>=2,<4']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jdavid\.conda\envs\conda-build310\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\jdavid\.conda\envs\conda-build310\lib\site-packages\conda_build\cli\main_build.py", line 593, in main
    execute(sys.argv[1:])
  File "C:\Users\jdavid\.conda\envs\conda-build310\lib\site-packages\conda_build\cli\main_build.py", line 573, in execute
    outputs = api.build(
  File "C:\Users\jdavid\.conda\envs\conda-build310\lib\site-packages\conda_build\api.py", line 253, in build
    return build_tree(
  File "C:\Users\jdavid\.conda\envs\conda-build310\lib\site-packages\conda_build\build.py", line 3799, in build_tree
    packages_from_this = build(
  File "C:\Users\jdavid\.conda\envs\conda-build310\lib\site-packages\conda_build\build.py", line 2469, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "C:\Users\jdavid\.conda\envs\conda-build310\lib\site-packages\conda_build\render.py", line 923, in expand_outputs
    for output_dict, m in deepcopy(_m).get_output_metadata_set(
  File "C:\Users\jdavid\.conda\envs\conda-build310\lib\site-packages\conda_build\metadata.py", line 2565, in get_output_metadata_set
    conda_packages = finalize_outputs_pass(
  File "C:\Users\jdavid\.conda\envs\conda-build310\lib\site-packages\conda_build\metadata.py", line 909, in finalize_outputs_pass
    fm = finalize_metadata(
  File "C:\Users\jdavid\.conda\envs\conda-build310\lib\site-packages\conda_build\render.py", line 637, in finalize_metadata
    build_unsat, host_unsat = add_upstream_pins(
  File "C:\Users\jdavid\.conda\envs\conda-build310\lib\site-packages\conda_build\render.py", line 478, in add_upstream_pins
    host_deps, host_unsat, extra_run_specs_from_host = _read_upstream_pin_files(
  File "C:\Users\jdavid\.conda\envs\conda-build310\lib\site-packages\conda_build\render.py", line 431, in _read_upstream_pin_files
    deps, actions, unsat = get_env_dependencies(
  File "C:\Users\jdavid\.conda\envs\conda-build310\lib\site-packages\conda_build\render.py", line 151, in get_env_dependencies
    actions = environ.get_install_actions(
  File "C:\Users\jdavid\.conda\envs\conda-build310\lib\site-packages\conda_build\environ.py", line 902, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform win-64: {"flit_core[version='>=2,<4']"}
PS C:\Users\jdavid\OneDrive - InnoPhase, Inc\PyProjects\anaconda>
**Environment:**
 - conda list
 # packages in environment at C:\Users\jdavid\.conda\envs\conda-build310:
#
# Name                    Version                   Build  Channel
beautifulsoup4            4.12.2          py310haa95532_0
blas                      1.0                         mkl
boltons                   23.0.0          py310haa95532_0
brotlipy                  0.7.0           py310h2bbff1b_1002
bzip2                     1.0.8                he774522_0
ca-certificates           2023.5.7             h56e8100_0    conda-forge
certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h2bbff1b_3
chardet                   4.0.0           py310haa95532_1003
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.0.4           py310haa95532_0
colorama                  0.4.6           py310haa95532_0
conda                     23.5.0          py310haa95532_0
conda-build               3.25.0          py310haa95532_0
conda-index               0.2.3           py310haa95532_0
conda-package-handling    2.1.0           py310haa95532_0
conda-package-streaming   0.8.0           py310haa95532_0
conda-souschef            2.2.3           py310haa95532_0
cryptography              39.0.1          py310h21b164f_2
filelock                  3.9.0           py310haa95532_0
flit-core                 3.9.0              pyhd8ed1ab_0    conda-forge
glob2                     0.7                pyhd3eb1b0_0
grayskull                 2.3.0           py310haa95532_0
idna                      3.4             py310haa95532_0
intel-openmp              2023.1.0         h59b6b97_46319
jinja2                    3.1.2           py310haa95532_0
jsonpatch                 1.32               pyhd3eb1b0_0
jsonpointer               2.1                pyhd3eb1b0_0
libarchive                3.6.2                hb62f4d4_2
libffi                    3.4.4                hd77b12b_0
libiconv                  1.16                 h2bbff1b_2
liblief                   0.12.3               hd77b12b_0
libxml2                   2.10.3               h0ad7f3c_0
lz4-c                     1.9.4                h2bbff1b_0
m2-msys2-runtime          2.5.0.17080.65c939c               3
m2-patch                  2.7.5                         2
markupsafe                2.1.1           py310h2bbff1b_0
menuinst                  1.4.19          py310h59b6b97_0
mkl                       2023.1.0         h8bd8f75_46356
mkl-service               2.4.0           py310h2bbff1b_1
mkl_fft                   1.3.6           py310h4ed8f06_1
mkl_random                1.2.2           py310h4ed8f06_1
more-itertools            8.12.0             pyhd3eb1b0_0
msys2-conda-epoch         20160418                      1
numpy                     1.25.0          py310h055cbcc_0
numpy-base                1.25.0          py310h65a83cf_0
openssl                   3.0.9                h2bbff1b_0
packaging                 23.0            py310haa95532_0
pip                       23.1.2          py310haa95532_0
pkginfo                   1.9.6           py310haa95532_0
pluggy                    1.0.0           py310haa95532_1
progressbar2              4.2.0           py310haa95532_0
psutil                    5.9.0           py310h2bbff1b_0
py-lief                   0.12.3          py310hd77b12b_0
pycosat                   0.6.4           py310h2bbff1b_0
pycparser                 2.21               pyhd3eb1b0_0
pyopenssl                 23.0.0          py310haa95532_0
pysocks                   1.7.1           py310haa95532_0
python                    3.10.11              he1021f5_3
python-libarchive-c       2.9                pyhd3eb1b0_1
python-utils              3.3.3           py310haa95532_0
pytz                      2022.7          py310haa95532_0
pyyaml                    6.0             py310h2bbff1b_1
rapidfuzz                 2.13.7          py310hc64d2fc_0
requests                  2.29.0          py310haa95532_0
ruamel.yaml               0.17.21         py310h2bbff1b_0
ruamel.yaml.clib          0.2.6           py310h2bbff1b_1
ruamel.yaml.jinja2        0.2.7           py310haa95532_0
semver                    2.13.0             pyhd3eb1b0_0
setuptools                67.8.0          py310haa95532_0
six                       1.16.0             pyhd3eb1b0_1
soupsieve                 2.4             py310haa95532_0
sqlite                    3.41.2               h2bbff1b_0
stdlib-list               0.8.0           py310haa95532_0
tbb                       2021.8.0             h59b6b97_0
tk                        8.6.12               h2bbff1b_0
tomli                     2.0.1           py310haa95532_0
tomli-w                   1.0.0              pyhd3eb1b0_0
toolz                     0.12.0          py310haa95532_0
tqdm                      4.65.0          py310h9909e9c_0
tzdata                    2023c                h04d1e81_0
urllib3                   1.26.16         py310haa95532_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.38.4          py310haa95532_0
win_inet_pton             1.1.0           py310haa95532_0
xz                        5.4.2                h8cc25b3_0
yaml                      0.2.5                he774522_0
zlib                      1.2.13               h8cc25b3_0
zstandard                 0.19.0          py310h2bbff1b_0
zstd                      1.5.5                hd43e919_0
 - pip list
 Package                 Version
----------------------- --------
beautifulsoup4          4.12.2
boltons                 23.0.0
brotlipy                0.7.0
certifi                 2023.5.7
cffi                    1.15.1
chardet                 4.0.0
charset-normalizer      2.0.4
click                   8.0.4
colorama                0.4.6
conda                   23.5.0
conda-build             3.25.0
conda_index             0.2.3
conda-package-handling  2.1.0
conda_package_streaming 0.8.0
conda-souschef          2.2.3
cryptography            39.0.1
filelock                3.9.0
flit_core               3.9.0
glob2                   0.7
grayskull               2.3.0
idna                    3.4
Jinja2                  3.1.2
jsonpatch               1.32
jsonpointer             2.1
libarchive-c            2.9
MarkupSafe              2.1.1
menuinst                1.4.19
mkl-fft                 1.3.6
mkl-random              1.2.2
mkl-service             2.4.0
more-itertools          8.12.0
numpy                   1.25.0
packaging               23.0
pip                     23.1.2
pkginfo                 1.9.6
pluggy                  1.0.0
progressbar2            4.2.0
psutil                  5.9.0
pycosat                 0.6.4
pycparser               2.21
pyOpenSSL               23.0.0
PySocks                 1.7.1
python-utils            3.3.3
pytz                    2022.7
PyYAML                  6.0
rapidfuzz               2.13.7
requests                2.29.0
ruamel.yaml             0.17.21
ruamel.yaml.clib        0.2.6
ruamel.yaml.jinja2      0.2.7
semver                  2.13.0
setuptools              67.8.0
six                     1.16.0
soupsieve               2.4
stdlib-list             0.8.0
tomli                   2.0.1
tomli_w                 1.0.0
toolz                   0.12.0
tqdm                    4.65.0
urllib3                 1.26.16
wheel                   0.38.4
win-inet-pton           1.1.0
zstandard               0.19.0
 - grayskull --version
2.3.0 
**Additional context**

**Comment by marcelotrevisani** [comment]
That was fixed already with
https://github.com/conda/grayskull/commit/65bcc1a6927662d7ff74a96764dede1fb03ca9e2

I will generate a new version that gonna have that fix in a couple days. Thanks for reporting it! :)
