### ISSUE TITLE
[BUG]  `*` version not correctly handled

### ISSUE THREAD

**Issue by dhirschfeld** [conda/grayskull#499]
**Describe the bug**
Over in https://github.com/conda-forge/quart-cors-feedstock/pull/14/files `update-grayskull` put in an update which *added* `- typing_extensions *` when `- typing-extensions` already existed, resulting in duplicate entries for `typing-extensions`:

![image](https://github.com/conda/grayskull/assets/881019/a09a4b99-5ac9-4969-a3eb-e11e8cc88e0a)

**Expected behavior**
`typing_extensions *` would be normalised to `typing_extensions` and therefore no update would be made to the existing dependencies (despite the `*` being in upstream - it should be recognised as equivalent)

https://github.com/pgjones/quart-cors/blob/0.7.0/pyproject.toml#L62

**Additional context**
It's a `poetry` dependency specification - maybe that's relevant?

**Comment by marcelotrevisani** [comment]
indeed, that is a problem, gonna put in my backlog, thanks for reporting it! :)

**Comment by marcelotrevisani** [comment]
That should be fixed with #503
